/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package exemplu_opendialog;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Radu
 */
public class Exemplu_OpenDialog extends javax.swing.JFrame
{

    /**
     * Creates new form Exemplu_OpenDialog
     */
    public Exemplu_OpenDialog()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        OpenButton = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10));
        SaveButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10));
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        text = new javax.swing.JTextArea();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10));
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Text Editor");
        setMinimumSize(new java.awt.Dimension(400, 300));
        setPreferredSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.X_AXIS));

        jPanel3.setMaximumSize(new java.awt.Dimension(10, 40000));
        jPanel3.setMinimumSize(new java.awt.Dimension(10, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(10, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 251, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        OpenButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        OpenButton.setText("Open");
        OpenButton.setAlignmentX(0.5F);
        OpenButton.setMaximumSize(new java.awt.Dimension(70, 30));
        OpenButton.setMinimumSize(new java.awt.Dimension(70, 30));
        OpenButton.setPreferredSize(new java.awt.Dimension(70, 30));
        OpenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenButtonActionPerformed(evt);
            }
        });
        jPanel1.add(OpenButton);
        jPanel1.add(filler2);

        SaveButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SaveButton.setText("Save");
        SaveButton.setAlignmentX(0.5F);
        SaveButton.setMaximumSize(new java.awt.Dimension(70, 30));
        SaveButton.setMinimumSize(new java.awt.Dimension(70, 30));
        SaveButton.setPreferredSize(new java.awt.Dimension(70, 30));
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SaveButton);

        getContentPane().add(jPanel1);

        jPanel4.setMaximumSize(new java.awt.Dimension(10, 40000));
        jPanel4.setMinimumSize(new java.awt.Dimension(10, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 251, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));
        jPanel2.add(filler1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Text:");
        jLabel1.setAlignmentX(0.5F);
        jPanel2.add(jLabel1);

        text.setColumns(20);
        text.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        text.setRows(5);
        text.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jScrollPane2.setViewportView(text);

        jPanel2.add(jScrollPane2);
        jPanel2.add(filler3);

        getContentPane().add(jPanel2);

        jPanel5.setMaximumSize(new java.awt.Dimension(10, 40000));
        jPanel5.setMinimumSize(new java.awt.Dimension(10, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 251, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OpenButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_OpenButtonActionPerformed
    {//GEN-HEADEREND:event_OpenButtonActionPerformed
        JFileChooser fc = new JFileChooser();
        
        fc.setAcceptAllFileFilterUsed(false);
        fc.setFileFilter(new FileNameExtensionFilter("Text Files (.txt)", "txt"));

        int r = fc.showOpenDialog(this);

        if (r == JFileChooser.APPROVE_OPTION) 
        {
            String nfis = fc.getSelectedFile().getAbsolutePath();
            
            try
            {
                Scanner in = new Scanner(new File(nfis));
                
                text.setText("");
                while(in.hasNextLine())
                {
                    String linie = in.nextLine();
                    text.append(linie + "\n");
                }
                
                in.close();
            } 
            catch (FileNotFoundException ex)
            {
                System.out.println("Eroare: " + ex);
            }
        }
    }//GEN-LAST:event_OpenButtonActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_SaveButtonActionPerformed
    {//GEN-HEADEREND:event_SaveButtonActionPerformed
        JFileChooser fc = new JFileChooser();
        
        fc.setAcceptAllFileFilterUsed(false);
        fc.setFileFilter(new FileNameExtensionFilter("Text Files (.txt)", "txt"));

        int r = fc.showSaveDialog(Exemplu_OpenDialog.this);

        if (r == JFileChooser.APPROVE_OPTION) 
        {
            String nfis = fc.getSelectedFile().getAbsolutePath();
            
            try
            {
                PrintWriter out = new PrintWriter(new File(nfis));
                
                out.print(text.getText());
                
                out.close();
            } 
            catch (FileNotFoundException ex)
            {
                System.out.println("Eroare: " + ex);
            }
        }
    }//GEN-LAST:event_SaveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
                if ("Windows".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Exemplu_OpenDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Exemplu_OpenDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Exemplu_OpenDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Exemplu_OpenDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Exemplu_OpenDialog().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OpenButton;
    private javax.swing.JButton SaveButton;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea text;
    // End of variables declaration//GEN-END:variables
}
