/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package baza_de_date_simpla;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cristina
 */
public class Tabel extends javax.swing.JFrame  {

    /**
     * Creates new form Tabel
     */
    Connection conn=null;
    
    public Tabel() {
        initComponents();
        try {
            Class.forName("com.mysql.jdbc.Driver");
        
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Tabel.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost/Angajati", "root", "12345");
        } catch (SQLException ex) {
            Logger.getLogger(Tabel.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabel = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        CNP_Nou = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        Nume_Nou = new javax.swing.JTextField();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        Varsta_nou = new javax.swing.JTextField();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        Salariu_Nou = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.X_AXIS));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        Tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CNP", "Nume", "Varsta", "Salariu"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabel);

        jPanel1.add(jScrollPane1);

        jButton1.setText("Afisare Angajati");
        jButton1.setAlignmentX(0.5F);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jTabbedPane1.addTab("Afisare date", jPanel1);

        jPanel2.setMaximumSize(new java.awt.Dimension(400, 300));
        jPanel2.setMinimumSize(new java.awt.Dimension(400, 300));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 300));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.X_AXIS));

        jPanel3.setMaximumSize(new java.awt.Dimension(200, 300));
        jPanel3.setMinimumSize(new java.awt.Dimension(200, 300));
        jPanel3.setPreferredSize(new java.awt.Dimension(200, 300));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Angajati");
        jLabel1.setAlignmentX(0.5F);
        jPanel3.add(jLabel1);

        jList1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jScrollPane2.setViewportView(jList1);

        jPanel3.add(jScrollPane2);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Stergere");
        jButton2.setAlignmentX(0.5F);
        jPanel3.add(jButton2);

        jPanel2.add(jPanel3);

        jPanel4.setMaximumSize(new java.awt.Dimension(200, 300));
        jPanel4.setMinimumSize(new java.awt.Dimension(200, 300));
        jPanel4.setPreferredSize(new java.awt.Dimension(200, 300));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));
        jPanel2.add(jPanel4);

        jTabbedPane1.addTab("Editare", jPanel2);

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.Y_AXIS));
        jPanel5.add(filler4);

        CNP_Nou.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CNP_Nou.setMaximumSize(new java.awt.Dimension(200, 20));
        CNP_Nou.setMinimumSize(new java.awt.Dimension(200, 20));
        CNP_Nou.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel5.add(CNP_Nou);
        jPanel5.add(filler1);

        Nume_Nou.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Nume_Nou.setMaximumSize(new java.awt.Dimension(200, 20));
        Nume_Nou.setMinimumSize(new java.awt.Dimension(200, 20));
        Nume_Nou.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel5.add(Nume_Nou);
        jPanel5.add(filler2);

        Varsta_nou.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Varsta_nou.setMaximumSize(new java.awt.Dimension(200, 20));
        Varsta_nou.setMinimumSize(new java.awt.Dimension(200, 20));
        Varsta_nou.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel5.add(Varsta_nou);
        jPanel5.add(filler3);

        Salariu_Nou.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Salariu_Nou.setMaximumSize(new java.awt.Dimension(200, 20));
        Salariu_Nou.setMinimumSize(new java.awt.Dimension(200, 20));
        Salariu_Nou.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel5.add(Salariu_Nou);

        jButton3.setText("jButton3");
        jPanel5.add(jButton3);

        jTabbedPane1.addTab("Introducere", jPanel5);

        getContentPane().add(jTabbedPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Statement st=conn.createStatement();
            
            String sql="SELECT * FROM date";
            ResultSet rs=st.executeQuery(sql);
            
            DefaultTableModel tm=(DefaultTableModel)Tabel.getModel();
            //se streg toate liniiile din tabel
            //se fol modelul de tabel
            while(tm.getRowCount()>0)
                tm.removeRow(0);
            
            //determinam numarul de coloane al rezulSet
            
            int nc=rs.getMetaData().getColumnCount();
            
            while(rs.next())
            {
                Object linie[]=new Object[nc];
                //se parcurge tabloul linie
                for(int i=0;i<nc;i++)
                    linie[i]=rs.getObject(i+1);//intoarce unobiect care este o celula din rs
            
                   tm.addRow(linie);
    
            }
            
   
        } catch (SQLException ex) {
            Logger.getLogger(Tabel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tabel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tabel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tabel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tabel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tabel().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CNP_Nou;
    private javax.swing.JTextField Nume_Nou;
    private javax.swing.JTextField Salariu_Nou;
    private javax.swing.JTable Tabel;
    private javax.swing.JTextField Varsta_nou;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
