INSERT INTO JOC_CATEGORIE ("JOC_CATEGORIE_ID", "NUME", "DESCRIERE") VALUES (1, 'Negotiation', 'Negotiation DESCRIERE');
INSERT INTO JOC_CATEGORIE ("JOC_CATEGORIE_ID", "NUME", "DESCRIERE") VALUES (2, 'Card Game', 'Card Game DESCRIERE.');
INSERT INTO JOC_CATEGORIE ("JOC_CATEGORIE_ID", "NUME", "DESCRIERE") VALUES (3, 'Territory Building', 'Territory Building DESCRIERE.');
INSERT INTO JOC_CATEGORIE ("JOC_CATEGORIE_ID", "NUME", "DESCRIERE") VALUES (4, 'Dice', 'Dice DESCRIERE.');