INSERT INTO ANDREEA."client" ("client_id", "name", "phone", "e-mail", "address") VALUES (1, 'Kevin Boyd', 2216710229, 'kboyd0@earthlink.net', '065 Manitowish Pass');
INSERT INTO ANDREEA."client" ("client_id", "name", "phone", "e-mail", "address") VALUES (2, 'Phillip Freeman', 2716054567, 'pfreeman1@home.pl', '4 Welch Hill');
INSERT INTO ANDREEA."client" ("client_id", "name", "phone", "e-mail", "address") VALUES (3, 'Victor Payne', 6049082392, 'vpayne2@dedecms.com', '82247 Holy Cross Trail');
INSERT INTO ANDREEA."client" ("client_id", "name", "phone", "e-mail", "address") VALUES (4, 'Jeremy Murphy', 4157948517, 'jmurphy3@amazonaws.com', '3 Hanover Plaza');
INSERT INTO ANDREEA."client" ("client_id", "name", "phone", "e-mail", "address") VALUES (5, 'Rachel Simmons', 5615061152, 'rsimmons4@gravatar.com', '2087 Shopko Trail');
INSERT INTO ANDREEA."client" ("client_id", "name", "phone", "e-mail", "address") VALUES (6, 'Craig Hughes', 7868020568, 'chughes5@virginia.edu', '6039 1st Trail');
INSERT INTO ANDREEA."client" ("client_id", "name", "phone", "e-mail", "address") VALUES (7, 'Barbara Greene', 9501037693, 'bgreene6@gizmodo.com', '1918 Riverside Street');
INSERT INTO ANDREEA."client" ("client_id", "name", "phone", "e-mail", "address") VALUES (8, 'Earl Hansen', 4474443631, 'ehansen7@washingtonpost.com', '895 Washington Terrace');
INSERT INTO ANDREEA."client" ("client_id", "name", "phone", "e-mail", "address") VALUES (9, 'Todd Bowman', 8864632825, 'tbowman8@over-blog.com', '0 Corscot Street');
INSERT INTO ANDREEA."client" ("client_id", "name", "phone", "e-mail", "address") VALUES (10, 'Karen Kelley', 9050554612, 'kkelley9@fda.gov', '7 Ridgeway Drive');
INSERT INTO ANDREEA."client" ("client_id", "name", "phone", "e-mail", "address") VALUES (11, 'Wayne Rose', 8981222919, 'wrosea@example.com', '5336 Maple Wood Pass');
INSERT INTO ANDREEA."client" ("client_id", "name", "phone", "e-mail", "address") VALUES (12, 'Jean Bishop', 9504305767, 'jbishopb@wordpress.com', '4074 7th Junction');
INSERT INTO ANDREEA."client" ("client_id", "name", "phone", "e-mail", "address") VALUES (13, 'Albert Burton', 1854829635, 'aburtonc@businesswire.com', '5 Sachs Terrace');
INSERT INTO ANDREEA."client" ("client_id", "name", "phone", "e-mail", "address") VALUES (14, 'Mary Lopez', 3864388201, 'mlopezd@auda.org.au', '695 Loomis Point');
INSERT INTO ANDREEA."client" ("client_id", "name", "phone", "e-mail", "address") VALUES (15, 'Walter Torres', 6546073895, 'wtorrese@wp.com', '95581 Haas Crossing');
INSERT INTO ANDREEA."client" ("client_id", "name", "phone", "e-mail", "address") VALUES (16, 'Judy Parker', 7856866581, 'jparkerf@barnesandnoble.com', '1 Anzinger Hill');
INSERT INTO ANDREEA."client" ("client_id", "name", "phone", "e-mail", "address") VALUES (17, 'Ruby Ramirez', 8584517138, 'rramirezg@patch.com', '91784 Onsgard Crossing');
INSERT INTO ANDREEA."client" ("client_id", "name", "phone", "e-mail", "address") VALUES (18, 'Harry Morgan', 8566602600, 'hmorganh@com.com', '639 Reindahl Crossing');
INSERT INTO ANDREEA."client" ("client_id", "name", "phone", "e-mail", "address") VALUES (19, 'Louis Hunt', 8803382414, 'lhunti@1und1.de', '9 Anhalt Alley');
INSERT INTO ANDREEA."client" ("client_id", "name", "phone", "e-mail", "address") VALUES (20, 'Gregory Matthews', 4824514426, 'gmatthewsj@bloomberg.com', '0 Hayes Crossing');
INSERT INTO ANDREEA."client" ("client_id", "name", "phone", "e-mail", "address") VALUES (21, 'Anthony Howell', 7157727836, 'ahowellk@baidu.com', '302 Northview Plaza');
INSERT INTO ANDREEA."client" ("client_id", "name", "phone", "e-mail", "address") VALUES (22, 'Bonnie Holmes', 6440327263, 'bholmesl@desdev.cn', '3823 Miller Road');
INSERT INTO ANDREEA."client" ("client_id", "name", "phone", "e-mail", "address") VALUES (23, 'Charles Sanders', 6701414958, 'csandersm@nbcnews.com', '67 Darwin Point');
INSERT INTO ANDREEA."client" ("client_id", "name", "phone", "e-mail", "address") VALUES (24, 'Mildred Larson', 6771932621, 'mlarsonn@cyberchimps.com', '27 Macpherson Pass');
INSERT INTO ANDREEA."client" ("client_id", "name", "phone", "e-mail", "address") VALUES (25, 'Phyllis Mills', 1090103695, 'pmillso@usgs.gov', '9 Mcguire Pass');
INSERT INTO ANDREEA."client" ("client_id", "name", "phone", "e-mail", "address") VALUES (26, 'Eugene King', 9382709514, 'ekingp@wired.com', '5505 Moland Plaza');
INSERT INTO ANDREEA."client" ("client_id", "name", "phone", "e-mail", "address") VALUES (27, 'Russell Fisher', 7615310238, 'rfisherq@free.fr', '1753 Crest Line Lane');
INSERT INTO ANDREEA."client" ("client_id", "name", "phone", "e-mail", "address") VALUES (28, 'Sarah Franklin', 9968250565, 'sfranklinr@uiuc.edu', '68932 Goodland Avenue');
INSERT INTO ANDREEA."client" ("client_id", "name", "phone", "e-mail", "address") VALUES (29, 'Pamela Mccoy', 5121855817, 'pmccoys@newsvine.com', '47 Shelley Plaza');
INSERT INTO ANDREEA."client" ("client_id", "name", "phone", "e-mail", "address") VALUES (30, 'Stephanie Wood', 1706526536, 'swoodt@printfriendly.com', '27 Nevada Alley');